site_name: MAP Narratives
repo_url: https://github.com/evomimic/map-narratives
repo_name: map-narratives
edit_uri: edit/main/docs/

plugins:
  - search
  #- pdf-export:
  #   verbose: true
  #    media_type: print

theme:
  name: material
  features:
    - navigation.instant
    - search.highlight
    - navigation.top
    - content.action.edit
  palette:
    - scheme: default
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.snippets:
      base_path: docs

nav:
  - Home: index.md

  - Drafts in Progress:
      - A New MAP Overview: drafts/overview.md
      - Collective Governance Scaffolds: drafts/collective-governance.md
      - MAP Promises: drafts/promises.md
      - Promise Weaves: drafts/promise-weaves.md
      - Vital Capital Flows: drafts/vital-capital-flows.md
      - Greet the DAHN: drafts/DAHN.md
      - Promise Agreements: drafts/promise-agreements.md
      - Uniform API (Dances): drafts/uniform-api.md
      - Ethical AI & RAG: drafts/ethical-ai-rag.md
      - Agreements, Agent Spaces and LifeCodes: drafts/agreements-spec.md
      - Glossary: drafts/glossary.md

  - MAP Dev Roadmap Planning:
      - Ecosystem Activation: dev-roadmap-planning/ecosystem-activation.md
      - HolonTypes: dev-roadmap-planning/holon-types.md
      - Mapps:
          - MVP Overview: dev-roadmap-planning/mapps/mapps-mvp.md
          - Calendar Adapter: dev-roadmap-planning/mapps/calendar-adapter.md
          - Geospatial Map Explorer: dev-roadmap-planning/mapps/geospatial-map-explorer.md
          - Holon Editor: dev-roadmap-planning/mapps/holon-editor.md
          - Holon Gallery: dev-roadmap-planning/mapps/holon-gallery.md
          - LifeCode Definer: dev-roadmap-planning/mapps/life-code-definer.md
          - MAP Navigator / Search: dev-roadmap-planning/mapps/map-navigator.md
          - Meme Pool Browser: dev-roadmap-planning/mapps/meme-pool-browser.md
          - Notification Center: dev-roadmap-planning/mapps/notification-center.md
          - Profile Manager: dev-roadmap-planning/mapps/profile-manager.md
          - Ritual Runner: dev-roadmap-planning/mapps/ritual-runner.md
          - Service Composer: dev-roadmap-planning/mapps/service-composer.md
          - Service Publisher: dev-roadmap-planning/mapps/service-publisher.md
          - Space Explorer: dev-roadmap-planning/mapps/space-explorer.md
          - Visualizer Commons: dev-roadmap-planning/mapps/visualizer-commons.md
      - Personas:
          - Persona Index: dev-roadmap-planning/personas/personas.md
          - Artist: dev-roadmap-planning/personas/artist.md
          - Bioregional Catalyst: dev-roadmap-planning/personas/bioregional-catalyst.md
          - Bridgewalker: dev-roadmap-planning/personas/bridgewalker.md
          - Cartographer: dev-roadmap-planning/personas/cartographer.md
          - Commons Architect: dev-roadmap-planning/personas/commons-architect.md
          - Community Weaver: dev-roadmap-planning/personas/community-weaver.md
          - Ecological Storyteller: dev-roadmap-planning/personas/ecological-storyteller.md
          - Embodied Practitioner: dev-roadmap-planning/personas/embodied-practitioner.md
          - Emergence Host: dev-roadmap-planning/personas/emergence-host.md
          - HX Designer: dev-roadmap-planning/personas/hx-designer.md
          - Landscape Steward: dev-roadmap-planning/personas/landscape-steward.md
          - Life Systems Educator: dev-roadmap-planning/personas/life-systems-educator.md
          - Mapp Developer: dev-roadmap-planning/personas/mapp-developer.md
          - Mythmaker: dev-roadmap-planning/personas/mythmaker.md
          - Pattern Detective: dev-roadmap-planning/personas/pattern-detective.md
          - Resource Connector: dev-roadmap-planning/personas/resource-connector.md
          - Ritual Holder: dev-roadmap-planning/personas/ritual-holder.md
          - Service Architect: dev-roadmap-planning/personas/service-architect.md
          - Signal Amplifier: dev-roadmap-planning/personas/signal-amplifier.md
          - Stewardship Crew: dev-roadmap-planning/personas/stewardship-crew.md
          - Techno-Doula: dev-roadmap-planning/personas/techno-doula.md
          - Thought Leader: dev-roadmap-planning/personas/thought-leader.md
          - Regenerative Actor: dev-roadmap-planning/personas/regenerative-actor.md
      - Use Case Model:
          - Use Case Model Overview: dev-roadmap-planning/use-cases/use-case-model.md
          - Accept Offer: dev-roadmap-planning/use-cases/accept-offer.md
          - Contribute Visualizer: dev-roadmap-planning/use-cases/contribute-visualizer.md
          - Create / View / Edit Holon: dev-roadmap-planning/use-cases/create-edit-holon.md
          - Create Space: dev-roadmap-planning/use-cases/create-space.md
          - Define / View / Edit LifeCode: dev-roadmap-planning/use-cases/define-life-code.md
          - Explore Geospatial Space: dev-roadmap-planning/use-cases/explore-geospatial-space.md
          - Handle Inbound Notification: dev-roadmap-planning/use-cases/handle-inbound-notification.md
          - Invite / Join Space: dev-roadmap-planning/use-cases/invite-join-space.md
          - Invite Others to Event: dev-roadmap-planning/use-cases/invite-to-event.md
          - Make Offer: dev-roadmap-planning/use-cases/make-offer.md
          - Navigate Space: dev-roadmap-planning/use-cases/navigate-space.md
          - Participate in Ritual: dev-roadmap-planning/use-cases/participate-in-ritual.md
          - Query Space: dev-roadmap-planning/use-cases/query-space.md
          - Receive Notifications: dev-roadmap-planning/use-cases/receive-notifications.md
          - RSVP to Event: dev-roadmap-planning/use-cases/rsvp-to-event.md
          - Schedule Event: dev-roadmap-planning/use-cases/schedule-event.md
          - View / Edit / Delete Holon: dev-roadmap-planning/use-cases/view-edit-delete-holon.md
          - View / Edit Notification Preferences: dev-roadmap-planning/use-cases/view-edit-notification-preferences.md
          - View / Edit Space Profile: dev-roadmap-planning/use-cases/view-edit-space-profile.md
          - View Holons in Space: dev-roadmap-planning/use-cases/view-holons-in-space.md
          - View Notifications: dev-roadmap-planning/use-cases/view-notifications.md

  - Archive:
      - GitBook Import: archive/gitbook-import.md